name: Blee Blog
description: Blog for getblee.com

url: http://brianmaierjr.github.com/long-haul
paginate_path: "/page:num/"
permalink: /:title/

markdown: redcarpet
pygments: true
paginate: 5

navigation:
 - title: Home
   url: /index.html
